owner: SanujaNS # Your GitHub organization or username, where this repository lives
repo: SanujaPut-Status # The name of this repository

sites:
  - name: My Gateway Website
    url: https://sanuja.biz/
    expectedStatusCodes:
      - 403
  - name: My Blog
    url: https://sanujas.com/
    expectedStatusCodes:
      - 403
  - name: SanujaPut-Music-1
    url: https://smusic.sanujas.eu.org/
  - name: SanujaPut-Music-2
    url: https://sanujas.serv00.net/
  - name: Lofi Beats
    url: https://sanuja.rf.gd/
    port: 443
    __dangerous__disable_verify_peer: true
  - name: YourIP
    url: https://sanuja.biz/projects/tools/yourip
    expectedStatusCodes:
      - 403
  - name: IPLookup
    url: https://sanuja.biz/projects/tools/iplookup
    expectedStatusCodes:
      - 403
  - name: YT Data Extractor
    url: https://yt.sanuja.eu.org/
  - name: File Downloader
    url: https://dl.sanuja.eu.org/
  - name: Oracle Files
    url: $ORACLE
    expectedStatusCodes:
      - 401
  - name: Private-DNS (ADGuard)
    url: $ADGUARD
    expectedStatusCodes:
      - 400

status-website:
  theme: dark
  cname: status.sanuja.biz
  # baseUrl: /your-repo-name
  logoUrl: https://sanuja.biz/images/logo.svg
  name: SanujaPut-Status
  faviconSvg: https://sanuja.biz/images/logo.svg
  introTitle: "**SanujaPut-Status** uptime monitor and status page."
  introMessage: This is uptime monitor and status page for services under [Sanuja Seneviratne](https://sanuja.biz/connect-me/).
  navbar:
    - title: Status
      href: /
    - title: Connect-Me
      href: https://sanuja.biz/connect-me/
