owner: SanujaNS # Your GitHub organization or username, where this repository lives
repo: SanujaPut-Status # The name of this repository

sites:
  - name: My Gateway Website
    url: https://sanuja.biz/
    expectedStatusCodes:
      - 403
  - name: My Blog
    url: https://sanujas.com/
    expectedStatusCodes:
      - 403
  - name: My Home Page
    url: https://status.sanuja.biz/
    expectedStatusCodes:
      - 403
  - name: SanujaPut-Music-1
    url: https://smusic.sanujas.eu.org/
  - name: SanujaPut-Music-2
    url: https://sanujas.serv00.net/
  - name: Lofi Beats
    url: https://sanuja.rf.gd/
    port: 443
    __dangerous__disable_verify_peer: true
  - name: Nightcore Music
    url: https://ncore.sanujas.eu.org/
  - name: YourIP
    url: https://sanuja.biz/projects/tools/yourip
    expectedStatusCodes:
      - 403
  - name: IPLookup
    url: https://sanuja.biz/projects/tools/iplookup
    expectedStatusCodes:
      - 403
  - name: YT Data Extractor
    url: https://yt.sanuja.eu.org/
  - name: Golden Maple Web Radio Player
    url: https://gm.sanuja.eu.org/
  - name: Sound Scenes
    url: https://ss.sanuja.eu.org/
  - name: SanujaPut_Bin (Pastebin Alternative)
    url: https://bin.sanuja.eu.org/
  - name: Social Media Downloader
    url: https://dl.sanuja.eu.org/
  #- name: Instagram Scraper
  #  url: https://nc.sanujas.com/
  #  expectedStatusCodes:
  #    - 403
  - name: Oracle File Index
    url: $ORACLE
    expectedStatusCodes:
      - 200
  - name: Private-DNS (ADGuard)
    url: $ADGUARD
    expectedStatusCodes:
      - 400

status-website:
  theme: dark
  cname: status.sanuja.biz
  # baseUrl: /your-repo-name
  logoUrl: https://sanuja.biz/images/status-logo.webp
  name: SanujaPut-Status
  favicon: https://sanuja.biz/images/status-logo.ico
  introTitle: "**SanujaPut-Status** uptime monitor and status page."
  introMessage: This is uptime monitor and status page for services under [Sanuja Seneviratne](https://sanuja.biz/).
  navbar:
    - title: Status
      href: /
    - title: Contacts
      href: https://sanuja.biz/connect-me/
